[project]
name = "order-status-lookup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Million", email = "millionabate19@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "mcp[cli]>=2.1.0",
]

[project.scripts]
order-status-lookup = "order_status_lookup:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
